name: Publish go-admin-doc CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --prod
    - name: Get Path
      run: pwd
    - name: Zip
      run: zip -r dist.zip ./docs/.vuepress/dist/*
    - name: Ls
      run: ls
    - name: 'Copy'
      uses: appleboy/ssh-action@master
      env:
        HOST: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        PORT: ${{ secrets.REMOTE_PORT }}
        SOURCE: ./dist.zip
        TARGET: /data/www/dist/
